const DEFAULT_ADMIN_GITHUB_USERNAME = 'REALEMMETTS';

export const ADMIN_GITHUB_USERNAME = (
  process.env.NEXT_PUBLIC_SUPABASE_ADMIN_GITHUB || DEFAULT_ADMIN_GITHUB_USERNAME
).toLowerCase();

export const ADMIN_GITHUB_USERNAME_DISPLAY =
  process.env.NEXT_PUBLIC_SUPABASE_ADMIN_GITHUB || DEFAULT_ADMIN_GITHUB_USERNAME;
